- kernel/apis/EnvironmentAPI.proto
- kernel/apis/ParcelIdentity.proto
- kernel/apis/Players.proto
- kernel/apis/UserIdentity.proto
- kernel/apis/common/ContentMapping.proto
- kernel/apis/common/UserData.proto
When trying to build the protocol with `protoc` I got a bunch of errors regarding re-defined messages in the kernel api proto files.
I moved the conflicting redefinitions to a common folder following the pattern you had for the ecs components shared structures.
I needed this to compile the protocol with Rust.
> Moved conflicting structures to kernel/api/common

- ecs/components/UiTransform.proto
- Update parent `int64` to `int32`
- Add RightOf prop
We need this props to generate the tree.
> add rightof prop to UITransform

- ecs/components/NFTShape.proto
since this change is breaking backward compatibility we should aim to merge it together with
js-sdk: https://github.com/decentraland/js-sdk-toolchain/pull/261
renderer: https://github.com/decentraland/unity-renderer/pull/3066
> fix: NFTShape ECS component

- proto/decentraland/sdk/components/ui_text.proto
*change UiText's `color` field type to `Color4`
sdk: https://github.com/decentraland/js-sdk-toolchain/pull/325
renderer: https://github.com/decentraland/unity-renderer/pull/3512
> fix: use Color4 for uiText color

- proto/decentraland/sdk/components/material.proto
This PR fixes [SDK issue #485](https://github.com/decentraland/sdk/issues/485) and adds the albedo_color property to BasicMaterial
> fix: add albedo color to BasicMaterial

- proto/decentraland/sdk/components/mesh_collider.proto
It was a misunderstanding. All colliders need to be explicitly created by scene creators to foster good performance practices
> remove all visible meshes

- proto/decentraland/social/friendships/friendships.proto
Each procedure will be updated to include the `Payload` parameter, allowing for individual authentication handling on each message. 
The idea is to revise this solution after Social Service M2 is released and then decide if better Authentication management can be done. So, the definition used is for internal use only, and the release will be marked as beta. The token in each message is strictly "optional", that would make it "always removable".
> feat: add auth token to each procedure 

- .devcontainer/devcontainer.json
- proto/decentraland/kernel/apis/environment_api.proto
- proto/decentraland/kernel/apis/restricted_actions.proto
- proto/decentraland/kernel/apis/runtime.proto
At the moment of writing this issue, we are implementing worker threads for the protocol squad. Currently the only way to get information of the scene is through the `GetBoostrapData` method. And to resolve the actual script of the scene, a regular `fetch` is required. Due to the constraints of the sandboxes of Decentraland, fetch is removed from the runtime unless explicitly requested via scene permisison. That is the motivation behind `Runtime.ReadFile`
> expand runtime

- proto/decentraland/social/friendships/friendships.proto
Remove error optional responses and instead allow procedures to return a Result<T, E> with a custom error type that implements RemoteError. This change will allow us to handle error responses and also handle some errors that may occur in the Rust RPC-Server. (See [link](https://github.com/decentraland/rpc-rust/pull/75) for more details.)
> refactor: remove error option response

- proto/decentraland/sdk/components/avatar_base.proto
- proto/decentraland/sdk/components/avatar_customization.proto
- proto/decentraland/sdk/components/avatar_emote_command.proto
- proto/decentraland/sdk/components/avatar_equipped_data.proto
- proto/decentraland/sdk/components/player_identity_data.proto
- public/sdk-components.proto
The original PR split: https://github.com/decentraland/protocol/pull/144
ADR https://github.com/decentraland/adr/pull/251 => https://089fff3d.adr-cvq.pages.dev/adr/ADR-245
These components are read-only for scenes. If you want to spawn a new own Avatar, you do it using the `AvatarShape` component.
The data of these components come from comms.
> feat: (sdk) add player and avatar components

- public/quests.proto
This PR: 
- makes quest definitions public and compiled :)
> fix: add quests defintions to public

- proto/decentraland/kernel/apis/runtime.proto
We had something similar in the `EnvironmentAPI` in SDK6.
It provides info about the current explorer
> feat: add `GetExplorerInformation` method in `~system/Runtime` api

- proto/decentraland/kernel/apis/runtime.proto
- proto/decentraland/kernel/apis/testing.proto
This API enables taking screenshots and comparing with a version stored by the explorer.
- You can make scene tests
- You can make explorer test by making `test-scenes`: https://github.com/decentraland/scene-explorer-tests/
This API is being used here:
https://github.com/decentraland/scene-explorer-tests/
For example, the GLTFContainer test:
- Code with the test: https://github.com/decentraland/scene-explorer-tests/blob/main/52%2C-62-gltf-container/src/tests/gltf-container/index.test.ts#L42
- Snapshot in Bevy: https://github.com/decentraland/bevy-explorer/blob/main/assets/images/screenshots/screenshot%252Fbevy_snapshot_gltfcontainer_avocado.png.png
- Snapshot in Godot: https://github.com/decentraland/godot-explorer/blob/main/tests/snapshots/screenshot_godot_snapshot_gltfcontainer_avocado.p …
> feat: testing api tool

- proto/decentraland/realm/about.proto
Following spec
https://github.com/decentraland/adr/pull/266
> feat: add adr content to specify the Map in any realms

- proto/decentraland/realm/about.proto
This "breaks" compatibility at formality-level but it doesn't at functionality-level.
The tool we use to check compatibility should support reserved keys: https://github.com/well-known-components/proto-compatibility-tool/blob/main/src/index.ts#L212
> chore: remove the usage of `reserved "key"`

- proto/decentraland/sdk/components/map_pin.proto
This PR adds support for the map pin component used internally for the exploration quests
> Feat: add map pin proto

- proto/decentraland/sdk/components/material.proto
Addresses the protocol part of [issue #240](https://github.com/decentraland/creator-hub/issues/240)
Related PRs:
E@: https://github.com/decentraland/unity-explorer/pull/2482
SDK: https://github.com/decentraland/js-sdk-toolchain/pull/1019
> chore: move alpha_texture from PBRMaterial to UnlitMaterial

- proto/decentraland/kernel/apis/restricted_actions.proto
Added avatar_target param in movePlayerTo() according to [ADR: 257](https://github.com/decentraland/adr/blob/main/content/ADR-257-avatar-rotation.md).
Related PRs:
* https://github.com/decentraland/js-sdk-toolchain/pull/1073
* https://github.com/decentraland/unity-explorer/pull/3328
> feat: avatar_target param addition in movePlayerTo

- proto/decentraland/social_service/v2/social_service_v2.proto
This PR adds the social settings RPC calls:
- GetSocialSettings: which gets all of the user's social settings.
- UpsertSocialSettings: which updates or inserts the user's social settings.
- GetPrivateMessagesSettings: which gets the preferences of any user in terms of receiving private messages from other people.
> feat: Social settings

- proto/decentraland/social_service/v2/social_service_v2.proto
This PR adds the `isFriend` property to the privacy settings response so the client can decide wether it can message someone or not if they have the only friends setting on.
> feat: Include is friend when asking for privacy settings

- proto/decentraland/sdk/components/realm_info.proto
Added documentation to realm info protobuf definition
> chore: added realminfo documentation

- proto/decentraland/kernel/comms/rfc4/comms.proto
This PR introduces a new optional from field in the Chat message defined in our protobuf protocol.
🎯 Purpose
As part of the Communities chat implementation, we’re introducing an intermediate actor — the Comms Message SFU — responsible for receiving messages from the client, validating the sender, resolving the list of community members, and then forwarding the message to the correct recipients.
Because the message is re-broadcasted by the SFU (instead of the original sender), the receiving clients would otherwise see the SFU as the sender. To preserve the identity of the original author, we’re adding the from field, allowing clients to properly render the original sender in the chat UI.
🧱 Changes
- Add optional from field to the Chat protobuf message
This change is backward-compatible, as …
> feat: Add optional from in chat

- proto/decentraland/sdk/components/gltf_node_modifiers.proto
- public/sdk-components.proto
Add new `GltfNodeModifiers` component structure.
Related PRs:
* https://github.com/decentraland/js-sdk-toolchain/pull/1156
* https://github.com/decentraland/protocol/pull/286
* https://github.com/decentraland/js-sdk-toolchain/pull/1158
* https://github.com/decentraland/sdk7-test-scenes/pull/32
* https://github.com/decentraland/unity-explorer/pull/4754
> feat: GltfNodeModifiers component

- proto/decentraland/sdk/components/mesh_collider.proto
- proto/decentraland/sdk/components/trigger_area.proto
- proto/decentraland/sdk/components/trigger_area_result.proto
`TriggerArea` and `TriggerAreaResult` messages implementation for the new components in the SDK.
Related PRs:
- https://github.com/decentraland/protocol/pull/307
- https://github.com/decentraland/js-sdk-toolchain/pull/1210
- https://github.com/decentraland/unity-explorer/pull/5244
- https://github.com/decentraland/sdk7-test-scenes/pull/34
> feat: trigger area components
