kernel/apis/EngineAPI.proto
kernel/apis/EnvironmentAPI.proto

reducing an entire back and forth.
Required for https://github.com/decentraland/kernel/pull/349

sendBatch and pullEvents can be simplified into only one method

---

ecs/components/AvatarAttach.proto

This will add an enum to the AvatarAttach so it is easier to understand what to add

feat: add enum for avatar attach component

---

renderer-protocol/EngineInterface.proto

Related to https://github.com/decentraland/sdk/issues/362

chore: add legacy protocol

---

ecs/components/MeshRenderer.proto

related to issue: https://github.com/decentraland/sdk/issues/366
adds `MeshRenderer` ecs component

feat: MeshRenderer ECS component

---

docs/Decentraland Protocol for Explorers.md

Add chat protocol description 
@guidota

Add chat protocol

---

ecs/components/Hidden.proto
ecs/components/VisibilityComponent.proto

Related to https://github.com/decentraland/sdk/issues/353

feat: add VisibilityComponent

---

ecs/components/MeshCollider.proto

js-sdk: https://github.com/decentraland/js-sdk-toolchain/pull/238

feat: MeshCollider ECS component

---

ecs/components/UiText.proto

https://github.com/decentraland/js-sdk-toolchain/pull/251

add uitext

---

ecs/components/UiStyles.proto
ecs/components/common/Color4.proto

Add `UiStyles` component for the UI.
We want to split the style component from the layout.
i.e.
```ts
<UiEntity uiTransform={{ width: 10 }} uiStyles={{ backgroundColor: { r: 1, g: 1, b: 2, a: 1 } } />
```

add ui styles component

---

kernel/comms/comms-rfc-4.proto

Reverts decentraland/protocol#52

Revert "add ping message"

---

proto/decentraland/sdk/components/ui_transform.proto

sdk: https://github.com/decentraland/js-sdk-toolchain/pull/320
renderer: https://github.com/decentraland/unity-renderer/pull/3378

fix: ui_transform optionals

---

proto/decentraland/sdk/components/raycast.proto

* SDK PR: https://github.com/decentraland/js-sdk-toolchain/pull/327
* Renderer PR: https://github.com/decentraland/unity-renderer/pull/3543

chore: remove timestamp from PBRaycast

---

proto/decentraland/kernel/apis/restricted_actions.proto
proto/decentraland/sdk/components/text_shape.proto

https://github.com/decentraland/sdk/issues/527

add new restricted actions

---

proto/decentraland/sdk/components/billboard.proto

Signed-off-by: menduz <github@menduz.com>

configurable billboard mode

---

proto/decentraland/sdk/components/material.proto

js-sdk: https://github.com/decentraland/js-sdk-toolchain/pull/376
renderer: https://github.com/decentraland/unity-renderer/pull/3890

fix: set `PbrMaterial.albedo_color` porperty as `Color4`

---

proto/decentraland/sdk/components/avatar_attach.proto

[issue](https://github.com/decentraland/sdk/issues/509)

Update AvatarAttach's 'avatar_id' to be optional

---

proto/decentraland/renderer/kernel_services/friends_kernel.proto
public/renderer-interface.proto

Adds the possibility to request the friendship status (none, friend, pending, etc) of a specific user.

feat: get friendship status

---

proto/decentraland/kernel/apis/environment_api.proto
proto/decentraland/kernel/apis/runtime.proto
public/sdk-apis.proto

Add runtime API for kernel <-> sdk

add runtime info to kernel api

---

proto/decentraland/common/texture.proto
proto/decentraland/sdk/components/video_player.proto

Protocol: https://github.com/decentraland/protocol/pull/96
Fix https://github.com/decentraland/sdk/issues/360

feat: video player component

---

proto/decentraland/sdk/components/ui_input.proto

added text_value string property for ui input protocol model to be able to change the ui input text value from the scene's code.
Related PRs:
* https://github.com/decentraland/js-sdk-toolchain/pull/448
* https://github.com/decentraland/unity-renderer/pull/4582

chore: ui input text value property

---

proto/decentraland/sdk/components/billboard.proto

Link new ADR and clarify additional restrictions

Update annotations in billboard.proto

---

proto/decentraland/sdk/components/mesh_collider.proto
proto/decentraland/sdk/components/mesh_renderer.proto

related to issue https://github.com/decentraland/sdk/issues/558

fix: sdk cylinder primitive radius default

---

proto/decentraland/social/friendships/friendships.proto

Handle errors from FriendshipsServiceServer messages, including Client and Server Errors

feat: friendship service error handling

---

proto/decentraland/social/friendships/friendships.proto

This reverts commit 9a568b16b2eafb134177329ba670c1451be8a169.

Revert "feat: add errors in social service response (#145)"

---

proto/decentraland/social/friendships/friendships.proto

This reverts commit 4b98e1a92f062036595ca092becc2a48f99be50d.

feat: add errors in social service response (#145)

---

proto/decentraland/common/texture.proto

Issue: https://github.com/decentraland/sdk/issues/516
Related PRs
* https://github.com/decentraland/js-sdk-toolchain/pull/594
* https://github.com/decentraland/unity-renderer/pull/5213

chore: remove texture mirror-once

---

proto/decentraland/kernel/apis/restricted_actions.proto

explorer: https://github.com/decentraland/unity-renderer/pull/5501

feat: add `TriggerSceneEmote` restricted action

---

proto/decentraland/kernel/apis/comms_api.proto
public/sdk-apis.proto

feat: add `CommsApiService` to kernel's api

---

proto/decentraland/kernel/apis/comms_api.proto

fix: add `source_type` to `VideoTracksActiveStreamsData` from `CommsApi`

---

proto/decentraland/kernel/apis/engine_api.proto

https://github.com/decentraland/scene-runtime/pull/206
https://github.com/decentraland/unity-renderer/pull/5620
https://github.com/decentraland/js-sdk-toolchain/pull/711

add is server API for sync servers

---

.github/workflows/build-and-publish.yml
proto/decentraland/sdk/components/ui_input_result.proto

* added 'is_submit' optional property in ui input result component
Related PRs
* https://github.com/decentraland/unity-renderer/pull/5864
* https://github.com/decentraland/js-sdk-toolchain/pull/809

feat: ui input submit

---

.github/workflows/build-and-publish.yml
proto/decentraland/kernel/apis/communications_controller.proto

https://github.com/decentraland/unity-renderer/pull/5822/files
https://github.com/decentraland/scene-runtime/pull/208
https://github.com/decentraland/js-sdk-toolchain/pull/790

[wip] message bus binary

---

proto/decentraland/kernel/comms/rfc4/comms.proto

protocol adjustments for explorer-alpha (first iteration)

Feat: E@ new proto messages (iteration I)

---

proto/decentraland/kernel/comms/rfc4/comms.proto

On unity-explorer side we now compressing and decompressing movement message, so I adjusted protocol with respect to this change

feat: adjusted proto for conpressed message

---

proto/decentraland/kernel/comms/rfc4/comms.proto

added support for rotation in uncompressed message

extended uncompressed message with rotation

---

proto/decentraland/common/texture.proto

Added offset and tiling optional properties to texture.proto

feat: texture mapping movement

---

proto/decentraland/common/texture.proto

Added documentation for new properties.

chore: add comments to clarify texture mapping process

---

Makefile
scripts/check-component-id.sh
scripts/list-components-ids.sh

Added a tool to list all the components ids in the terminal.
Added a tool to check if a given id is free or taken.

chore: added component id tools

---

proto/decentraland/sdk/components/light_source.proto

chore: dynamic lights cookies

---

proto/decentraland/sdk/components/virtual_camera.proto

Adding `fov` field for SDK's VirtualCamera component.
Related PRs:
* https://github.com/decentraland/js-sdk-toolchain/pull/1076
* https://github.com/decentraland/unity-explorer/pull/3487

feat: virtual camera fov parameter

---

proto/decentraland/sdk/components/ui_transform.proto

Addresses the protocol implementation for issues
https://github.com/decentraland/unity-explorer/issues/4088
https://github.com/decentraland/unity-explorer/issues/4090
Related PRs:
E@: https://github.com/decentraland/unity-explorer/pull/4366
SDK: wip

feat: z index and opacity for uielements

---

proto/decentraland/sdk/components/avatar_shape.proto

Issue: https://github.com/decentraland/unity-explorer/issues/4742
Explorer: https://github.com/decentraland/unity-explorer/pull/4811
SDK: https://github.com/decentraland/js-sdk-toolchain/pull/1165

feat: invisible body through PBAvatarShape

---

.github/workflows/validate.yml
Makefile
scripts/check-proto-compabitility.sh

Ensuring compatibility checks run against the correct target branch

fix experimental validate check
